# Generated by Django 5.2.10 on 2026-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_supabase_uid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
