# Generated by Django 5.2.5 on 2026-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_supabase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_delivery_used',
            field=models.BooleanField(default=False),
        ),
    ]
