# Generated by Django 5.2.5 on 2026-02-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_supabase_uid', models.CharField(db_index=True, max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('issue_type', models.CharField(choices=[('delivery', 'Delivery Issue'), ('food_quality', 'Food Quality'), ('app_issue', 'App Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
