# Generated by Django 5.2.11 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status', 'is_active'], name='shops_status_1f86fc_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['town', 'status'], name='shops_town_efc911_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['owner_supabase_uid'], name='shops_owner_s_eede40_idx'),
        ),
    ]
