# Generated by Django 5.2.5 on 2026-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_online_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rider_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
