# Generated by Django 5.2.5 on 2026-01-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_enrolled_user_rider_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_addresses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
