# Generated by Django 5.2.5 on 2026-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_saved_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_orders_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
