# Generated by Django 5.2.5 on 2026-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_reward_points_user_total_orders_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_deliveries_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='free_deliveries_used',
            field=models.IntegerField(default=0),
        ),
    ]
