# Generated by Django 5.2.5 on 2026-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(default='TownBasket', max_length=100)),
                ('is_open_for_delivery', models.BooleanField(default=True)),
                ('night_orders_enabled', models.BooleanField(default=False)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('default_delivery_charge', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Town Settings',
                'db_table': 'town_settings',
            },
        ),
    ]
