# Generated by Django 5.2.11 on 2026-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_uid', models.CharField(db_index=True, max_length=255)),
                ('admin_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['admin_uid', 'created_at'], name='audit_logs_admin_u_98fa49_idx')],
            },
        ),
    ]
