# Generated by Django 5.2.11 on 2026-02-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('order_spike', 'Order Spike'), ('high_cancel_rate', 'High Cancel Rate'), ('rapid_orders', 'Rapid Sequential Orders'), ('high_refund_rate', 'High Refund Rate'), ('suspicious_pattern', 'Suspicious Pattern')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('dismissed', 'Dismissed'), ('confirmed', 'Confirmed')], default='active', max_length=15)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, default='', help_text='Groups related admin actions within a session', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['risk_level', 'created_at'], name='audit_logs_risk_le_6c799c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['session_id'], name='audit_logs_session_632f07_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status', 'severity', '-created_at'], name='fraud_alert_status_642d97_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='fraud_alert_alert_t_687b34_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['target_type', 'target_id'], name='fraud_alert_target__10a652_idx'),
        ),
    ]
