# Generated by Django 5.2.11 on 2026-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fraudalert_auditlog_risk_level_auditlog_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='alert_type',
            field=models.CharField(choices=[('order_spike', 'Order Spike'), ('high_cancel_rate', 'High Cancel Rate'), ('rapid_orders', 'Rapid Sequential Orders'), ('high_refund_rate', 'High Refund Rate'), ('suspicious_pattern', 'Suspicious Pattern'), ('high_complaint_ratio', 'High Complaint Ratio'), ('repeated_refunds', 'Repeated Refunds'), ('rapid_account_creation', 'Rapid Account Creation')], db_index=True, max_length=30),
        ),
    ]
