# Generated by Django 5.2.11 on 2026-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scale_indexes_and_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMetricsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('avg_delivery_minutes', models.FloatField(default=0)),
                ('complaints_total', models.IntegerField(default=0)),
                ('complaints_pending', models.IntegerField(default=0)),
                ('active_shops', models.IntegerField(default=0)),
                ('shops_with_orders', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_metrics_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='idx_metrics_date_desc')],
            },
        ),
    ]
